Repository hyperledger/aries-framework-go, pull requests merged in 2019-08, with the labels that each got.

#75 (#73) Add contrib, issue, and PR guidelines
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#91 doc: Project Build information
  README.md
Labels: documentation

#88 feat: Framework Init - base template with Outbound transport config
  pkg/didcomm/protocol/exchange/exchange.go
  pkg/didcomm/protocol/exchange/exchange_test.go
  pkg/framework/aries/api/factory.go
  pkg/framework/aries/default.go
  pkg/framework/aries/factory/transport/transport_factory.go
  pkg/framework/aries/factory/transport/transport_factory_test.go
  pkg/framework/aries/framework.go
  pkg/framework/aries/framework_test.go
  pkg/framework/context/context.go
  pkg/framework/context/context_test.go
Labels: enhancement

#107 feat: Authcrypt Encrypt Using (X)Chach20Poly1035
  go.mod
  go.sum
  pkg/didcomm/crypto/crypter.go
  pkg/didcomm/crypto/jwe/authcrypt/authcrypt.go
  pkg/didcomm/crypto/jwe/authcrypt/authcrypt_test.go
  pkg/didcomm/crypto/jwe/authcrypt/decrypt.go
  pkg/didcomm/crypto/jwe/authcrypt/encrypt.go
Labels: enhancement

#193 test: Update leveldb path for test run
  cmd/aries-agentd/main_test.go
  pkg/framework/aries/default.go
  pkg/framework/aries/framework_test.go
  pkg/restapi/restapi_test.go
Labels: bug
