Repository hyperledger/aries-framework-go, pull requests merged in 2020-09, with the labels that each got.

#2162 fix: agent-rest - database timeout flag name
  cmd/aries-agent-rest/go.mod
  cmd/aries-agent-rest/go.sum
  cmd/aries-agent-rest/startcmd/start.go
Labels: bug

#2167 chore: Update to Go 1.15
  .github/workflows/build.yml
  .github/workflows/test-suite.yml
  Makefile
  ci/azure-pipelines.yml
  cmd/aries-agent-mobile/go.mod
  cmd/aries-agent-mobile/go.sum
  cmd/aries-agent-rest/go.mod
  cmd/aries-js-worker/README.md
  docs/test/build.md
  go.mod
  test/bdd/go.mod
  test/bdd/go.sum
Labels: chore

#2180 fix: #2178 CouchDB setup in BDD tests
  pkg/storage/base58wrapper/base58wrapper_test.go
  pkg/storage/couchdb/couchdbstore.go
  pkg/storage/couchdb/couchdbstore_test.go
  pkg/storage/providers_test.go
  scripts/check_js_integration.sh
  scripts/check_unit.sh
  scripts/couchdb-config/10-single-node.ini
  test/bdd/fixtures/agent-rest/couchdb-config/10-single-node.ini
  test/bdd/fixtures/agent-rest/docker-compose.yml
Labels: bug

#2182 fix: unit tests depending on docker
  .github/workflows/build.yml
  pkg/storage/base58wrapper/base58wrapper_test.go
  pkg/storage/couchdb/couchdbstore.go
  pkg/storage/couchdb/couchdbstore_test.go
  pkg/storage/mysql/mysqlstore_test.go
  pkg/storage/providers_test.go
  pkg/storage/store_test.go
  scripts/check_unit.sh
Labels: bug

#2187 chore: go mod tidy
  cmd/aries-agent-mobile/README.md
  cmd/aries-agent-mobile/go.sum
  cmd/aries-agent-rest/go.mod
  cmd/aries-agent-rest/go.sum
  cmd/aries-js-worker/go.mod
  cmd/aries-js-worker/go.sum
  test/bdd/go.sum
Labels: chore

#2189 doc: Present Proof - REST usage
  docs/rest/openapi_demo.md
Labels: documentation

#2190 test: Fixes local KMS writer test
  pkg/kms/localkms/localkms_writer_test.go
Labels: bug

#2195 doc: Issue Credential - REST usage
  docs/rest/openapi_demo.md
Labels: documentation

#2196 doc: Present Proof - improves formatting
  docs/rest/openapi_demo.md
Labels: documentation

#2206 chore: update codecov-action version
  .github/workflows/build.yml
Labels: chore
