Repository hyperledger/aries-framework-go, pull requests merged in 2020-06, with the labels that each got.

#1953 bug: remove nolint gosec and fix possible sql injection vulnerability
  pkg/storage/mysql/mysqlstore.go
  pkg/storage/mysql/mysqlstore_test.go
Labels: bug, priority

#1954 Revert "bug: remove nolint gosec and fix possible sql injection attack"
  pkg/storage/mysql/mysqlstore.go
  pkg/storage/mysql/mysqlstore_test.go
Labels: bug, needs fix

#1951 feat: add core ECDH-1PU key wrapping and unwrapping
  cmd/aries-agent-rest/go.sum
  cmd/aries-js-worker/go.sum
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_aes_aead_private_key_manager.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_aes_aead_private_key_manager_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_aes_aead_public_key_manager.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_aes_aead_public_key_manager_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_factory_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_key_template.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_key_template_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/subtle/ecdh1pu_aes_aead_composite_decrypt.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/subtle/ecdh1pu_aes_aead_composite_encrypt.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/subtle/ecdh1pu_aes_aead_composite_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/subtle/ecdhes_1pukdf_recipient_kuw.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/subtle/ecdhes_1pukdf_sender_kw.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_aes_aead_public_key_manager.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_aes_aead_public_key_manager_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_factory_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_key_template.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_concatkdf_sender_kw.go
  pkg/crypto/tinkcrypto/primitive/proto/common_composite_go_proto/common_composite.pb.go
  pkg/crypto/tinkcrypto/primitive/proto/ecdh1pu_aead_go_proto/ecdh1pu_aead.pb.go
  pkg/crypto/tinkcrypto/primitive/proto/ecdhes_aead_go_proto/ecdhes_aead.pb.go
  pkg/internal/cryptoutil/utils.go
  protos/tink/README.md
  protos/tink/common_composite.proto
  protos/tink/ecdh1pu_aead.proto
  protos/tink/ecdhes_aead.proto
  test/bdd/go.mod
  test/bdd/go.sum
Labels: enhancement

#1949 feat: Common notifier for the protocols
  Makefile
  pkg/client/outofband/example_test.go
  pkg/controller/command/didexchange/command_test.go
  pkg/controller/command/introduce/command.go
  pkg/controller/command/introduce/command_test.go
  pkg/controller/command/issuecredential/command.go
  pkg/controller/command/issuecredential/command_test.go
  pkg/controller/command/outofband/command.go
  pkg/controller/command/outofband/command_test.go
  pkg/controller/command/presentproof/command.go
  pkg/controller/command/presentproof/command_test.go
  pkg/controller/controller.go
  pkg/controller/rest/introduce/operation.go
  pkg/controller/rest/introduce/operation_test.go
  pkg/controller/rest/issuecredential/operation.go
  pkg/controller/rest/issuecredential/operation_test.go
  pkg/controller/rest/outofband/operation.go
  pkg/controller/rest/outofband/operation_test.go
  pkg/controller/rest/presentproof/operation.go
  pkg/controller/rest/presentproof/operation_test.go
  pkg/controller/webnotifier/observer.go
  pkg/controller/webnotifier/observer_test.go
  pkg/didcomm/common/service/did_comm_msg.go
  pkg/didcomm/common/service/did_comm_msg_test.go
  pkg/didcomm/common/service/event.go
  pkg/didcomm/common/service/service_test.go
  pkg/didcomm/messenger/messenger.go
  pkg/didcomm/protocol/didexchange/event.go
  pkg/didcomm/protocol/didexchange/event_test.go
  pkg/didcomm/protocol/didexchange/service.go
  pkg/didcomm/protocol/introduce/service.go
  pkg/didcomm/protocol/issuecredential/service.go
  pkg/didcomm/protocol/issuecredential/service_test.go
  pkg/didcomm/protocol/outofband/service.go
  pkg/didcomm/protocol/presentproof/service.go
  pkg/didcomm/protocol/presentproof/service_test.go
  pkg/internal/gomocks/controller/webnotifier/mocks.go
  pkg/mock/didcomm/protocol/didexchange/mock_didexchange.go
  test/aries-js-worker/test/didexchange/didexchange_e2e.js
Labels: enhancement

#1956 feat: Common notifier for the didexchange
  pkg/controller/command/didexchange/command.go
  pkg/controller/command/didexchange/command_test.go
  pkg/controller/command/didexchange/models.go
  pkg/didcomm/protocol/didexchange/service.go
  test/aries-js-worker/test/didexchange/didexchange_e2e.js
  test/aries-js-worker/test/didexchange/edgeagent_mediator.js
  test/bdd/pkg/didexchange/didexchange_controller_steps.go
Labels: enhancement

#1962 feat: Present Proof - added correlation id
  pkg/controller/command/presentproof/command.go
  pkg/controller/command/presentproof/models.go
  pkg/controller/rest/presentproof/models.go
  pkg/didcomm/protocol/presentproof/properties.go
  pkg/didcomm/protocol/presentproof/properties_test.go
  pkg/didcomm/protocol/presentproof/service.go
  test/bdd/go.mod
  test/bdd/pkg/didexchange/didexchange_controller_steps.go
  test/bdd/pkg/introduce/introduce_controller_steps.go
  test/bdd/pkg/issuecredential/issuecredential_controller_steps.go
  test/bdd/pkg/mediator/mediator_controller_steps.go
  test/bdd/pkg/messaging/messaging_controller_steps.go
  test/bdd/pkg/outofband/outofband_controller_steps.go
  test/bdd/pkg/presentproof/presentproof_controller_steps.go
  test/bdd/pkg/sidetree/sidetree.go
  test/bdd/pkg/util/util.go
Labels: enhancement
