Repository hyperledger/aries-framework-go, pull requests merged in 2020-08, with the labels that each got.

#2107 feat: #2105 presentation-exchange: get matching credentials
  cmd/aries-agent-mobile/go.sum
  cmd/aries-agent-rest/go.sum
  go.mod
  go.sum
  pkg/doc/presexch/api.go
  pkg/doc/presexch/api_test.go
  pkg/doc/presexch/example_test.go
  test/bdd/go.sum
Labels: enhancement

#2113 fix: #2078 #2112
  cmd/aries-js-worker/go.sum
  pkg/doc/signature/suite/ed25519signature2018/suite.go
  pkg/kms/legacykms/kms.go
  pkg/vdri/registry.go
  pkg/vdri/verifiable_compat_test.go
Labels: bug

#2120 feat: Present proof - adds examples
  pkg/client/presentproof/example_test.go
  pkg/didcomm/protocol/presentproof/states.go
  pkg/didcomm/protocol/presentproof/states_test.go
Labels: bug

#2126 docs: Present Proof documentation (godoc)
  pkg/client/presentproof/doc.go
Labels: documentation

#2139 fix: Fixes deadline in BDD test
  test/bdd/pkg/introduce/introduce_controller_steps.go
  test/bdd/pkg/introduce/introduce_sdk_steps.go
Labels: bdd
