Repository hyperledger/aries-framework-go, pull requests merged in 2020-12, with the labels that each got.

#2373 chore: add duration logs for webkms calls
  pkg/crypto/webkms/remotecrypto.go
  pkg/kms/webkms/crypto_box.go
  pkg/kms/webkms/remotekms.go
Labels: enhancement

#2392 feat: Defines PresentationDefinition fields according to spec
  pkg/doc/presexch/api.go
  pkg/doc/presexch/api_test.go
  pkg/doc/presexch/example_test.go
Labels: aip 2.0, refactor

#2394 test: add webkms test cases in bdd tests
  cmd/aries-agent-mobile/go.sum
  cmd/aries-agent-rest/go.sum
  cmd/aries-js-worker/go.sum
  scripts/generate_test_keys.sh
  test/bdd/agent/agent_sdk_steps.go
  test/bdd/features/didexchange_e2e_sdk.feature
  test/bdd/fixtures/agent-rest/.env
  test/bdd/fixtures/agent-rest/couchdb-config/10-single-node.ini
  test/bdd/fixtures/agent-rest/docker-compose.yml
  test/bdd/go.sum
Labels: bdd
