Repository hyperledger/aries-framework-go, pull requests merged in 2020-10, with the labels that each got.

#2211 fix: Mediator - replacing a channel sync with the database sync
  .github/workflows/build.yml
  pkg/didcomm/protocol/mediator/service.go
  pkg/didcomm/protocol/mediator/service_test.go
Labels: bug

#2212 fix: Fixes MySQL iterator
  pkg/storage/mysql/mysqlstore.go
  pkg/storage/store_test.go
Labels: bug

#2213 test: BDD tests for multiple router support
  pkg/didcomm/protocol/presentproof/service_test.go
  test/aries-js-worker/test/didexchange/edgeagent_mediator.js
  test/bdd/features/aries_mediator_e2e_controller.feature
  test/bdd/features/aries_mediator_e2e_sdk.feature
  test/bdd/pkg/didexchange/didexchange_controller_steps.go
  test/bdd/pkg/didexchange/didexchange_sdk_steps.go
  test/bdd/pkg/mediator/mediator_controller_steps.go
Labels: bdd

#2219 refactor: BDD/Unit tests improvements
  cmd/aries-agent-mobile/go.mod
  cmd/aries-agent-mobile/go.sum
  cmd/aries-agent-rest/go.sum
  cmd/aries-js-worker/go.sum
  go.mod
  go.sum
  pkg/didcomm/common/service/did_comm_msg.go
  pkg/storage/couchdb/couchdbstore_test.go
  pkg/storage/mysql/mysqlstore_test.go
  pkg/storage/providers_test.go
  pkg/storage/wrapper/prefix/prefix_wrapper_test.go
  scripts/check_unit.sh
  test/aries-js-worker/test/didexchange/didexchange_e2e.js
  test/aries-js-worker/test/didexchange/edgeagent_mediator.js
  test/aries-js-worker/test/introduce/introduce.js
  test/aries-js-worker/test/outofband/outofband.js
  test/bdd/fixtures/agent-rest/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
Labels: wip

#2233 refactor: Go BDD tests improvements
  test/bdd/features/aries_mediator_e2e_sdk.feature
  test/bdd/pkg/context/context.go
  test/bdd/pkg/didexchange/didexchange_sdk_steps.go
  test/bdd/pkg/introduce/introduce_controller_steps.go
  test/bdd/pkg/introduce/introduce_sdk_steps.go
  test/bdd/pkg/mediator/mediator_sdk_steps.go
  test/bdd/pkg/messaging/messaging_controller_steps.go
  test/bdd/pkg/outofband/outofband_sdk_steps.go
  test/bdd/pkg/redeemableroutes/redeemable_routes.go
  test/bdd/pkg/util/util.go
Labels: bdd

#2232 chore: Github - environment variables
  .github/workflows/build.yml
Labels: chore

#2226 fix: Couchdb - document update conflict
  pkg/storage/couchdb/couchdbstore.go
  pkg/storage/couchdb/couchdbstore_test.go
Labels: bug

#2163 Forward: Fix json keys
  pkg/didcomm/common/model/forward.go
Labels: stale

#2285 feat: #2284 add capabilityChain for LD Proofs
  cmd/aries-agent-mobile/go.mod
  cmd/aries-agent-mobile/go.sum
  cmd/aries-agent-rest/go.sum
  pkg/doc/signature/proof/proof.go
  pkg/doc/signature/proof/proof_test.go
  pkg/doc/signature/signer/signer.go
  pkg/doc/verifiable/common.go
  pkg/doc/verifiable/credential_ldp_test.go
  pkg/doc/verifiable/linked_data_proof.go
Labels: enhancement
