Repository hyperledger/aries-framework-go, pull requests merged in 2021-06, with the labels that each got.

#2809 feat: RFC0593 REST API
  cmd/aries-agent-rest/startcmd/start.go
  cmd/aries-agent-rest/startcmd/start_test.go
  pkg/client/issuecredential/rfc0593/event.go
  pkg/client/issuecredential/rfc0593/event_test.go
  pkg/client/issuecredential/rfc0593/middleware.go
  pkg/controller/command/errors.go
  pkg/controller/command/issuecredential/command.go
  pkg/controller/command/issuecredential/command_test.go
  pkg/controller/command/rfc0593/command.go
  pkg/controller/command/rfc0593/models.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/rest/issuecredential/operation.go
  pkg/controller/rest/issuecredential/operation_test.go
  pkg/controller/rest/rfc0593/models.go
  pkg/controller/rest/rfc0593/operation.go
  pkg/controller/rest/rfc0593/operation_test.go
  pkg/didcomm/protocol/issuecredential/states.go
  test/bdd/bddtests_test.go
  test/bdd/features/issue_credential_controller.feature
  test/bdd/features/rfc0593_controller.feature
  test/bdd/fixtures/agent-rest/docker-compose.yml
  test/bdd/pkg/issuecredential/issuecredential_controller_steps.go
  test/bdd/pkg/presentproof/presentproof_sdk_steps.go
  test/bdd/pkg/rfc0593/steps_go.go
  test/bdd/pkg/rfc0593/steps_rest.go
Labels: aip 2.0

#2811 feat: add CBC+HMAC Tink Key
  pkg/crypto/tinkcrypto/primitive/aead/aead.go
  pkg/crypto/tinkcrypto/primitive/aead/aead_factory.go
  pkg/crypto/tinkcrypto/primitive/aead/aead_factory_test.go
  pkg/crypto/tinkcrypto/primitive/aead/aead_key_templates.go
  pkg/crypto/tinkcrypto/primitive/aead/aead_key_templates_test.go
  pkg/crypto/tinkcrypto/primitive/aead/aead_test.go
  pkg/crypto/tinkcrypto/primitive/aead/aes_cbc_hmac_aead_key_manager.go
  pkg/crypto/tinkcrypto/primitive/aead/aes_cbc_hmac_aead_key_manager_test.go
  pkg/crypto/tinkcrypto/primitive/aead/subtle/aes_cbc.go
  pkg/crypto/tinkcrypto/primitive/aead/subtle/aes_cbc_test.go
  pkg/crypto/tinkcrypto/primitive/aead/subtle/gojose_aes_cbc_hmac.go
  pkg/crypto/tinkcrypto/primitive/aead/subtle/gojose_aes_cbc_hmac_test.go
  pkg/crypto/tinkcrypto/primitive/aead/subtle/subtle.go
  pkg/crypto/tinkcrypto/primitive/aead/subtle/subtle_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_key_template.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_key_template_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh/subtle/ecdh_aes_aead_composite_encrypt.go
  pkg/crypto/tinkcrypto/primitive/composite/register_ecdh_aead_enc_helper.go
  pkg/crypto/tinkcrypto/primitive/composite/register_ecdh_aead_enc_helper_test.go
  pkg/crypto/tinkcrypto/primitive/proto/aes_cbc_go_proto/aes_cbc.pb.go
  pkg/crypto/tinkcrypto/primitive/proto/aes_cbc_hmac_aead_go_proto/aes_cbc_hmac_aead.pb.go
  pkg/crypto/tinkcrypto/primitive/proto/bbs_go_proto/bbs.pb.go
  pkg/crypto/tinkcrypto/primitive/proto/ecdh_aead_go_proto/ecdh_aead.pb.go
  proto/tink/README.md
  proto/tink/aes_cbc.proto
  proto/tink/aes_cbc_hmac_aead.proto
  proto/tink/bbs.proto
  proto/tink/ecdh_aead.proto
Labels: enhancement

#2813 fix: CreateKeyStore returns an error.
  pkg/kms/webkms/remotekms.go
  pkg/kms/webkms/remotekms_test.go
Labels: bug

#2827 chore: udpate CBC+HMAC padding
  pkg/crypto/tinkcrypto/primitive/aead/aead_factory.go
  pkg/crypto/tinkcrypto/primitive/aead/aead_factory_test.go
  pkg/crypto/tinkcrypto/primitive/aead/aead_key_templates_test.go
  pkg/crypto/tinkcrypto/primitive/aead/aead_test.go
  pkg/crypto/tinkcrypto/primitive/aead/subtle/aes_cbc.go
  pkg/crypto/tinkcrypto/primitive/aead/subtle/aes_cbc_test.go
Labels: refactor

#2851 feat: enable ecdh-1pu draft4 JWE decryption test
  pkg/crypto/tinkcrypto/primitive/aead/subtle/aes_cbc_test.go
  pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export.go
  pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export_import_test.go
  pkg/crypto/tinkcrypto/primitive/composite/register_ecdh_aead_enc_helper.go
  pkg/didcomm/packer/anoncrypt/pack.go
  pkg/didcomm/packer/authcrypt/pack.go
  pkg/doc/jose/decrypter.go
  pkg/doc/jose/encrypt_test.go
  pkg/doc/jose/encrypter.go
  pkg/doc/jose/encrypter_decrypter_test.go
Labels: aip 2.0, enhancement
