Repository hyperledger/aries-framework-go, pull requests merged in 2021-02, with the labels that each got.

#2498 fix: json tags
  pkg/didcomm/protocol/outofband/models.go
  pkg/doc/did/doc.go
Labels: aip 2.0, bug

#2497 fix: single recipient JWE with AAD decrypt error
  pkg/doc/jose/decrypter.go
  pkg/doc/jose/encrypter.go
  pkg/doc/jose/encrypter_decrypter_test.go
  pkg/doc/util/jwkkid/kid_creator.go
Labels: bug

#2526 feat: RFC0360 use-did-key
  cmd/aries-js-worker/go.sum
  pkg/client/didexchange/client.go
  pkg/client/messaging/client.go
  pkg/client/messaging/client_test.go
  pkg/client/outofband/client.go
  pkg/controller/command/messaging/command_test.go
  pkg/controller/rest/messaging/operation_test.go
  pkg/didcomm/common/service/destination_test.go
  pkg/didcomm/dispatcher/outbound.go
  pkg/didcomm/dispatcher/outbound_test.go
  pkg/didcomm/packager/package_test.go
  pkg/didcomm/packager/packager.go
  pkg/didcomm/protocol/didexchange/service_test.go
  pkg/didcomm/protocol/didexchange/states.go
  pkg/didcomm/protocol/didexchange/states_test.go
  pkg/didcomm/protocol/mediator/service.go
  pkg/didcomm/protocol/mediator/service_test.go
  pkg/didcomm/transport/ws/pool.go
  pkg/didcomm/transport/ws/pool_test.go
  pkg/doc/did/doc.go
  pkg/doc/did/helpers.go
  pkg/doc/did/helpers_test.go
  pkg/framework/aries/framework_test.go
  pkg/mock/diddoc/mock_diddoc.go
  pkg/store/did/didconnection_test.go
  pkg/vdr/fingerprint/fingerprint.go
  pkg/vdr/peer/creator.go
  pkg/vdr/peer/creator_test.go
  test/bdd/pkg/messaging/messaging_steps.go
  test/bdd/pkg/sidetree/sidetree.go
Labels: aip 2.0, enhancement

#2523 feat: add integrity headers in JWE/DIDComm
  pkg/crypto/tinkcrypto/key_wrapper.go
  pkg/didcomm/packer/anoncrypt/pack.go
  pkg/didcomm/packer/anoncrypt/pack_test.go
  pkg/didcomm/packer/authcrypt/pack.go
  pkg/didcomm/packer/authcrypt/pack_test.go
  pkg/doc/jose/decrypter.go
  pkg/doc/jose/encrypt_test.go
  pkg/doc/jose/encrypter.go
  pkg/doc/jose/encrypter_decrypter_test.go
  pkg/doc/jose/jwe.go
  pkg/doc/jose/jwe_test.go
Labels: enhancement

#2533 fix: wrong Ed25519 KID value
  pkg/client/didexchange/client_test.go
  pkg/controller/command/didexchange/command_test.go
  pkg/didcomm/packer/legacy/authcrypt/authcrypt_test.go
  pkg/doc/util/jwkkid/kid_creator.go
  pkg/doc/util/jwkkid/kid_creator_test.go
  pkg/kms/localkms/kid_creator_test.go
  test/bdd/features/didexchange_e2e_sdk.feature
Labels: bug, enhancement

#2538 feat: add BBS+ Tink protos
  cmd/aries-js-worker/go.mod
  cmd/aries-js-worker/go.sum
  go.mod
  pkg/crypto/tinkcrypto/primitive/proto/bbs_go_proto/bbs.pb.go
  pkg/crypto/tinkcrypto/primitive/proto/ecdh_aead_go_proto/ecdh_aead.pb.go
  proto/tink/README.md
  proto/tink/bbs.proto
  proto/tink/ecdh_aead.proto
Labels: enhancement

#2550 feat: KMS support for BBS+ keys: create Tink key managers
  cmd/aries-js-worker/go.sum
  pkg/crypto/tinkcrypto/primitive/bbs/api/signer.go
  pkg/crypto/tinkcrypto/primitive/bbs/api/verifier.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_signer_key_manager.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_signer_key_manager_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_verifier_key_manager.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_verifier_key_manager_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/subtle/bls12381g2_signer.go
  pkg/crypto/tinkcrypto/primitive/bbs/subtle/bls12381g2_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/subtle/bls12381g2_verifier.go
  pkg/crypto/tinkcrypto/primitive/proto/bbs_go_proto/bbs.pb.go
  proto/tink/README.md
  proto/tink/bbs.proto
Labels: enhancement

#2560 feat: add BBS Tink primitives factories
  cmd/aries-js-worker/go.sum
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_primitive_factory_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_signer_factory.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_verifier_factory.go
Labels: enhancement

#2565 feat:KMS support for BBS+ keys: create Tink key templates
  pkg/crypto/tinkcrypto/primitive/bbs/bbs.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_key_template.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_key_template_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_signer_key_manager.go
Labels: enhancement

#2568 feat:KMS support for BBS+ keys: support Public key export, Private Key Import
  pkg/doc/util/jwkkid/kid_creator.go
  pkg/doc/util/jwkkid/kid_creator_test.go
  pkg/kms/api.go
  pkg/kms/localkms/localkms.go
  pkg/kms/localkms/localkms_test.go
  pkg/kms/localkms/privkey_import.go
  pkg/kms/localkms/pubkey_export_import_test.go
  pkg/kms/localkms/pubkey_reader.go
  pkg/kms/localkms/pubkey_writer.go
Labels: enhancement

#2570 refactor: move bbs12381g2pub to pkg/crypto
  .github/workflows/bbs-interop.yml
  .golangci.yml
  cmd/aries-js-worker/go.sum
  pkg/crypto/api.go
  pkg/crypto/primitive/bbs12381g2pub/bbs.go
  pkg/crypto/primitive/bbs12381g2pub/bbs_test.go
  pkg/crypto/primitive/bbs12381g2pub/fr.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/README.md
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/arithmetic_fallback.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/bls12_381.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/field_element.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/field_element_test.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/fp.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/fp_fallback.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/fp_test.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/g1.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/g1_custom.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/g1_custom_test.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/hash_to_field_custom.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/isogeny.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/swu.go
  pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/utils.go
  pkg/crypto/primitive/bbs12381g2pub/keys.go
  pkg/crypto/primitive/bbs12381g2pub/keys_test.go
  pkg/crypto/primitive/bbs12381g2pub/proof_of_knowledge.go
  pkg/crypto/primitive/bbs12381g2pub/signature.go
  pkg/crypto/primitive/bbs12381g2pub/signature_message.go
  pkg/crypto/primitive/bbs12381g2pub/signature_proof.go
  pkg/crypto/primitive/bbs12381g2pub/signature_test.go
  pkg/crypto/primitive/bbs12381g2pub/utils.go
  pkg/crypto/primitive/bbs12381g2pub/utils_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_primitive_factory_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_signer_key_manager.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs_verifier_key_manager_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/subtle/bls12381g2_signer.go
  pkg/crypto/tinkcrypto/primitive/bbs/subtle/bls12381g2_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/subtle/bls12381g2_verifier.go
  pkg/doc/bbs/api.go
  pkg/doc/presexch/definition_test.go
  pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go
  pkg/doc/signature/verifier/public_key_verifier.go
  pkg/doc/util/jwkkid/kid_creator_test.go
  pkg/doc/verifiable/credential_bbs_test.go
  pkg/doc/verifiable/credential_ldp_test.go
  pkg/doc/verifiable/example_support_test.go
  pkg/kms/localkms/localkms.go
  pkg/kms/localkms/localkms_test.go
  pkg/kms/localkms/privkey_import.go
  test/bbs/src/main.go
  test/bbs/src/support_signer.go
Labels: refactor
