Repository hyperledger/aries-framework-go, pull requests merged in 2021-03, with the labels that each got.

#2574 feat: add BBS+ support to crypto.Crypto and webkms
  pkg/crypto/api.go
  pkg/crypto/primitive/bbs12381g2pub/bbs.go
  pkg/crypto/tinkcrypto/crypto.go
  pkg/crypto/tinkcrypto/crypto_test.go
  pkg/crypto/tinkcrypto/primitive/bbs/bbs.go
  pkg/crypto/webkms/remotecrypto.go
  pkg/crypto/webkms/remotecrypto_test.go
  pkg/mock/crypto/mock_crypto.go
Labels: enhancement

#2581 fix: BBS+ DeriveProof panic
  pkg/crypto/primitive/bbs12381g2pub/bbs.go
  pkg/crypto/primitive/bbs12381g2pub/bbs_test.go
  pkg/crypto/primitive/bbs12381g2pub/proof_of_knowledge.go
  pkg/crypto/primitive/bbs12381g2pub/utils.go
  pkg/crypto/primitive/bbs12381g2pub/utils_test.go
Labels: bug

#2590 perf: boost ECDH key creation for Primitive execution
  pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_key_template_test.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_nistpkw_private_key_manager.go
  pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_x25519kw_private_key_manager.go
Labels: enhancement

#2594 feat: add BBS and NISTP did key creation
  pkg/doc/util/jwkkid/kid_creator.go
  pkg/vdr/fingerprint/fingerprint.go
  pkg/vdr/fingerprint/fingerprint_test.go
  pkg/vdr/key/creator.go
  pkg/vdr/key/creator_test.go
  pkg/vdr/key/resolver.go
  pkg/vdr/key/resolver_test.go
  pkg/vdr/key/vdr.go
Labels: enhancement

#2603 fix: did.Doc.UnmarshalJSON panic if parsing fails
  pkg/doc/did/doc.go
  pkg/doc/did/doc_test.go
Labels: bug

#2623 fix: json tags for issuecredV2 and presentproofV2
  pkg/didcomm/protocol/issuecredential/models.go
  pkg/didcomm/protocol/presentproof/models.go
  test/bdd/pkg/issuecredential/issuecredential_controller_steps.go
Labels: aip 2.0, bug

#2626 feat: presexch - parse VCs with proofs
  pkg/doc/presexch/api.go
  pkg/doc/presexch/api_test.go
  pkg/doc/presexch/example_test.go
Labels: aip 2.0, enhancement

#2625 refactor: replace all json-gold Doc Loaders with Framework's impl
  cmd/aries-agent-mobile/go.mod
  cmd/aries-agent-mobile/go.sum
  cmd/aries-agent-rest/go.mod
  cmd/aries-agent-rest/go.sum
  cmd/aries-js-worker/go.sum
  component/storageutil/go.mod
  component/storageutil/go.sum
  go.mod
  go.sum
  pkg/controller/command/verifiable/command.go
  pkg/didcomm/protocol/middleware/presentproof/middlewares.go
  pkg/doc/jsonld/jsonld.go
  pkg/doc/presexch/api_test.go
  pkg/doc/presexch/definition.go
  pkg/doc/presexch/definition_test.go
  pkg/doc/presexch/example_test.go
  pkg/doc/signature/jsonld/processor_test.go
  pkg/doc/verifiable/example_support_test.go
  pkg/doc/verifiable/jsonld.go
  pkg/doc/verifiable/jsonld_test.go
  pkg/doc/verifiable/support_test.go
  pkg/secretlock/local/masterlock/pbkdf2/master_secret_lock_test.go
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/presentproof/presentproof_sdk_steps.go
  test/component/go.mod
  test/component/go.sum
Labels: chore, refactor

#2630 chore: presexch - expose JSONSchema, add JSONLD context
  pkg/doc/presexch/api.go
  pkg/doc/presexch/definition.go
  pkg/doc/presexch/schema.go
Labels: aip 2.0, chore

#2634 fix: /verifiable/presentation/generate: load presentation-exchange JSONLD context
  pkg/controller/command/verifiable/command.go
Labels: bug

#2671 fix: ineffective didexchange.Client.CreateConnection()
  pkg/didcomm/protocol/didexchange/service.go
  pkg/didcomm/protocol/didexchange/service_test.go
Labels: bug

#2701 feat: outofband.Invitation.Accept and media types
  pkg/client/outofband/client.go
  pkg/didcomm/common/service/destination.go
  pkg/didcomm/dispatcher/outbound.go
  pkg/didcomm/packager/package_test.go
  pkg/didcomm/packager/packager.go
  pkg/didcomm/packer/anoncrypt/pack.go
  pkg/didcomm/packer/anoncrypt/pack_test.go
  pkg/didcomm/packer/authcrypt/pack.go
  pkg/didcomm/packer/authcrypt/pack_test.go
  pkg/didcomm/packer/legacy/authcrypt/unpack.go
  pkg/didcomm/protocol/didexchange/models.go
  pkg/didcomm/protocol/didexchange/service.go
  pkg/didcomm/protocol/outofband/models.go
  pkg/didcomm/protocol/outofband/service.go
  pkg/didcomm/transport/media_type.go
  pkg/didcomm/transport/transport_interface.go
  pkg/doc/did/doc.go
  pkg/framework/context/context.go
  pkg/mock/didcomm/packer/noop.go
  pkg/mock/didcomm/packer/noop_test.go
  pkg/store/connection/connection_lookup.go
  test/aries-js-worker/package-lock.json
Labels: aip 2.0, enhancement

#2705 feat: #2701 save inbound didexchange.Request envelope media type into connection record
  pkg/client/didexchange/client.go
  pkg/client/didexchange/client_test.go
  pkg/client/introduce/example_test.go
  pkg/client/issuecredential/example_test.go
  pkg/client/messaging/client_test.go
  pkg/client/messaging/msgservice.go
  pkg/client/messaging/msgservice_test.go
  pkg/client/presentproof/client.go
  pkg/client/presentproof/client_test.go
  pkg/client/presentproof/example_test.go
  pkg/controller/command/didexchange/command_test.go
  pkg/controller/command/presentproof/command_test.go
  pkg/didcomm/common/service/messenger.go
  pkg/didcomm/common/service/messenger_test.go
  pkg/didcomm/common/service/service.go
  pkg/didcomm/messaging/service/basic/basicmsgsvc.go
  pkg/didcomm/messaging/service/basic/basicmsgsvc_test.go
  pkg/didcomm/messaging/service/http/httpmsgsvc.go
  pkg/didcomm/messaging/service/http/httpmsgsvc_test.go
  pkg/didcomm/messenger/messenger.go
  pkg/didcomm/messenger/messenger_test.go
  pkg/didcomm/protocol/didexchange/service.go
  pkg/didcomm/protocol/didexchange/service_test.go
  pkg/didcomm/protocol/introduce/service.go
  pkg/didcomm/protocol/introduce/service_test.go
  pkg/didcomm/protocol/issuecredential/service.go
  pkg/didcomm/protocol/issuecredential/service_test.go
  pkg/didcomm/protocol/mediator/service.go
  pkg/didcomm/protocol/mediator/service_test.go
  pkg/didcomm/protocol/messagepickup/service.go
  pkg/didcomm/protocol/messagepickup/service_test.go
  pkg/didcomm/protocol/outofband/service.go
  pkg/didcomm/protocol/outofband/service_test.go
  pkg/didcomm/protocol/presentproof/service.go
  pkg/didcomm/protocol/presentproof/service_test.go
  pkg/framework/context/context.go
  pkg/framework/context/context_test.go
  pkg/internal/gomocks/client/introduce/mocks.gen.go
  pkg/internal/gomocks/client/issuecredential/mocks.gen.go
  pkg/internal/gomocks/client/presentproof/mocks.gen.go
  pkg/internal/gomocks/didcomm/common/service/mocks.gen.go
  pkg/mock/didcomm/protocol/didexchange/mock_didexchange.go
  pkg/mock/didcomm/protocol/generic/mock_generic_svc.go
  pkg/mock/didcomm/protocol/mediator/mock_mediator.go
  pkg/mock/didcomm/protocol/messagepickup/mock_messagepickup.go
  test/bdd/pkg/messaging/messaging_sdk_steps.go
  test/bdd/pkg/messaging/msgservice.go
Labels: aip 2.0, enhancement
