Repository hyperledger/aries-framework-go, pull requests merged in 2021-04, with the labels that each got.

#2729 feat: RFC0434 out-of-band - support connection reuse
  cmd/aries-agent-mobile/go.mod
  cmd/aries-agent-mobile/go.sum
  cmd/aries-agent-rest/go.mod
  cmd/aries-agent-rest/go.sum
  cmd/aries-js-worker/go.mod
  go.mod
  go.sum
  pkg/client/outofband/client.go
  pkg/client/outofband/client_test.go
  pkg/client/outofband/example_test.go
  pkg/controller/command/outofband/command.go
  pkg/controller/command/outofband/command_test.go
  pkg/controller/command/outofband/models.go
  pkg/controller/rest/outofband/models.go
  pkg/controller/rest/outofband/operation_test.go
  pkg/didcomm/protocol/didexchange/service.go
  pkg/didcomm/protocol/didexchange/states.go
  pkg/didcomm/protocol/didexchange/states_test.go
  pkg/didcomm/protocol/introduce/service.go
  pkg/didcomm/protocol/introduce/service_test.go
  pkg/didcomm/protocol/mediator/service.go
  pkg/didcomm/protocol/outofband/models.go
  pkg/didcomm/protocol/outofband/service.go
  pkg/didcomm/protocol/outofband/service_test.go
  pkg/didcomm/protocol/outofband/states.go
  pkg/didcomm/protocol/outofband/states_test.go
  pkg/framework/aries/api/protocol.go
  pkg/framework/context/context.go
  pkg/framework/context/context_test.go
  pkg/internal/gomocks/client/outofband/mocks.gen.go
  pkg/mock/didcomm/protocol/mock_protocol.go
  pkg/mock/didcomm/protocol/outofband/outofband.go
  pkg/mock/didcomm/service/mock_service.go
  test/bdd/bddtests_test.go
  test/bdd/features/introduce.feature
  test/bdd/features/outofband_controller.feature
  test/bdd/features/outofband_e2e_sdk.feature
  test/bdd/features/redeemable_routes.feature
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/introduce/introduce_sdk_steps.go
  test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go
  test/bdd/pkg/outofband/outofband_sdk_steps.go
  test/bdd/pkg/redeemableroutes/redeemable_routes.go
Labels: aip 2.0, enhancement

#2740 fix: media types not fetched from connection when initiating protocol
  pkg/client/outofband/client.go
  pkg/didcomm/common/service/destination.go
  pkg/didcomm/common/service/messenger.go
  pkg/didcomm/dispatcher/outbound.go
  pkg/didcomm/dispatcher/outbound_test.go
  pkg/didcomm/packager/package_test.go
  pkg/didcomm/packager/packager.go
  pkg/didcomm/packer/anoncrypt/pack.go
  pkg/didcomm/packer/anoncrypt/pack_test.go
  pkg/didcomm/packer/authcrypt/pack.go
  pkg/didcomm/packer/authcrypt/pack_test.go
  pkg/didcomm/packer/legacy/authcrypt/unpack.go
  pkg/didcomm/protocol/didexchange/models.go
  pkg/didcomm/protocol/didexchange/service.go
  pkg/didcomm/protocol/didexchange/service_test.go
  pkg/didcomm/protocol/didexchange/states.go
  pkg/didcomm/protocol/didexchange/states_test.go
  pkg/didcomm/protocol/outofband/service.go
  pkg/didcomm/protocol/outofband/service_test.go
  pkg/didcomm/transport/media_type.go
  pkg/didcomm/transport/transport_interface.go
  pkg/framework/aries/framework.go
  pkg/framework/context/context.go
  pkg/store/connection/connection_lookup.go
  pkg/store/connection/connection_lookup_test.go
  pkg/store/connection/connection_recorder_test.go
Labels: aip 2.0, chore

#2753 fix: presexch - CreateVP() matching schema URI algo
  .github/workflows/build.yml
  docs/test/bdd_tests.md
  pkg/client/vcwallet/client_test.go
  pkg/didcomm/protocol/middleware/presentproof/middlewares_test.go
  pkg/doc/presexch/definition.go
  pkg/doc/presexch/definition_test.go
  pkg/doc/presexch/example_test.go
  pkg/wallet/query_test.go
  pkg/wallet/wallet_test.go
  test/aries-js-worker/fixtures/docker-compose.yml
  test/aries-js-worker/test/presentproof/presentproof.js
  test/bdd/fixtures/agent-rest/docker-compose.yml
  test/bdd/fixtures/agent-rest/schema/schema.json
  test/bdd/pkg/presentproof/presentproof_controller_steps.go
  test/bdd/pkg/presentproof/presentproof_sdk_steps.go
  test/bdd/pkg/presentproof/testdata/presentation_bbs.json
  test/bdd/pkg/presentproof/testdata/presentation_multiple_attachments.json
  test/bdd/pkg/presentproof/testdata/request_presentation_bbs.json
  test/bdd/pkg/presentproof/testdata/request_presentation_multiple_attachments.json
Labels: aip 2.0, bug

#2755 fix: presentation-exchange schema.uri matching
  pkg/client/vcwallet/client_test.go
  pkg/didcomm/protocol/middleware/presentproof/middlewares_test.go
  pkg/doc/presexch/api.go
  pkg/doc/presexch/api_test.go
  pkg/doc/presexch/definition.go
  pkg/doc/presexch/definition_test.go
  pkg/doc/presexch/example_test.go
  pkg/wallet/query_test.go
  pkg/wallet/wallet_test.go
  test/aries-js-worker/test/presentproof/presentproof.js
  test/bdd/pkg/presentproof/presentproof_sdk_steps.go
  test/bdd/pkg/presentproof/testdata/request_presentation_bbs.json
Labels: aip 2.0, bug

#2743 feat: add KeyAgreement to DIDDoc and variable key type
  pkg/client/didexchange/client.go
  pkg/client/didexchange/client_test.go
  pkg/controller/command/didexchange/command.go
  pkg/controller/command/didexchange/command_test.go
  pkg/controller/command/vdr/command_test.go
  pkg/controller/rest/didexchange/operation.go
  pkg/crypto/eckey.go
  pkg/crypto/eckey_test.go
  pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export.go
  pkg/didcomm/common/service/destination_test.go
  pkg/didcomm/protocol/didexchange/keys.go
  pkg/didcomm/protocol/didexchange/keys_test.go
  pkg/didcomm/protocol/didexchange/service.go
  pkg/didcomm/protocol/didexchange/service_test.go
  pkg/didcomm/protocol/didexchange/states.go
  pkg/didcomm/protocol/didexchange/states_test.go
  pkg/doc/did/doc.go
  pkg/doc/did/doc_test.go
  pkg/doc/did/testdata/invalid_doc.jsonld
  pkg/doc/did/testdata/valid_doc.jsonld
  pkg/doc/did/testdata/valid_doc_with_base.jsonld
  pkg/doc/jose/jwk.go
  pkg/doc/jose/jwk_test.go
  pkg/doc/util/kmsdidkey/kmsdidkey.go
  pkg/doc/util/kmsdidkey/kmsdidkey_test.go
  pkg/doc/verifiable/credential_jwt_proof_test.go
  pkg/framework/aries/api/protocol.go
  pkg/framework/aries/default.go
  pkg/framework/aries/framework.go
  pkg/framework/aries/framework_test.go
  pkg/framework/context/context.go
  pkg/framework/context/context_test.go
  pkg/mock/didcomm/protocol/mock_protocol.go
  pkg/mock/provider/mock_provider.go
  pkg/store/did/store_test.go
  pkg/vdr/peer/creator.go
  pkg/vdr/peer/creator_test.go
  pkg/vdr/peer/did_test.go
  pkg/vdr/registry.go
  pkg/vdr/verifiable_compat_test.go
  test/aries-js-worker/test/vdr/vdr.js
Labels: aip 2.0, enhancement
